#                                                                         |
#  	__  __    _______    _     _ _     _     ___    ___                   |
# 	|  \/  |  |__   __|  | |   | (_)   | |   |__ \  / _ \                 |
# 	| \  / |_   _| | __ _| |__ | |_ ___| |_     ) || | | |                |
# 	| |\/| | | | | |/ _` | '_ \| | / __| __|   / / | | | |                |
# 	| |  | | |_| | | (_| | |_) | | \__ \ |_   / /_ | |_| |                |
# 	|_|  |_|\__, |_|\__,_|_.__/|_|_|___/\__| |____(_)___/                 |
# 	         __/ |                                                        |
# 	        |___/                                                         |
#                                                                         |
#                                                                         |
#  MyTablist2 Version 2.3.7 by DevXPress (derbl4ck)                   	  |
#																		                                      |
# ------------------------------------------------------------------------
#
# Properties:
#

# We use Plugin Metrics to collect Information about the Usage of the Plugin. That's just basic Information: System OS, Bukkit version, plugin version etc.
useMetrics: true

# This plugin has an easy API to add new Variables to this plugin. Let this true if you want that other plugins can add variables
useAPI: true

# This plugin has an Automatic plugin Updater. It will download the latest version into /plugins/updater and Install it automatically after the next reload/restart.
useAutoUpdater: true

# Download and Install the newest version of the plugin Automatically if enabled. If false you will just become a Message that a new Version is Available.
autodownload: true

# Enable autoRefresh to set the Refresh Interval of the Tablist. Otherwise the Tablist will be only Updated when a Player Joins, Disconnects or Changes the world.
autoRefresh: false

# Refresh the tablist each x Seconds
refreshInterval: 10

# If enabled the rest of the tablist will be filled with empty slots. Otherwise the last entry/player will be the last slot.
pingseption: false

# If enabled the Display Name (Colored or modified name) will be used in the Tablist. Otherwise the Unmodified Name will be used.
useDisplayNames: true

#
# Check out the Variables at:
# http://dev.bukkit.org/bukkit-plugins/mytablist/pages/variables/
#
# ColorCodes are supported with '&' + Code.
#
# You can set 5 self defined variables too!
#
# Get it with %var1%,%var2%,%var3%...

Customvars:
  '1': ''
  '2': ''
  '3': ''
  '4': ''
  '5': ''

# You can check if a Player is Online WITH %player1%, %player2%, %player3%...
# (Max 5 players)
#

Players:
  '1': ''
  '2': ''
  '3': ''
  '4': ''
  '5': ''

# You can Display online users of a Group with %group1.1%, %group1.2%, %group1.3%, %group1.4%, %group1.5%, the same for %group2.1%, ...
# eg. %group1.1% is Member 1 of group Admins. This will display the first user of a group who is online -> TheGameHacker
# (max 2 Groups, 5 displayed users)
#

Groups:
  '1': 'Admins'
  '2': 'Mods'

#
# Define some custom Tablist's for each world:
#
# You can use one Config for several worlds.
# You can add groups
#For examlpe, to use remove #
Configs:
#  main:
#    - world
#    - world_nether
#    - world_the_end
# -> world, world_nether, world_the_end use /MyTabList2/worlds/main.yml!
#
# IMPORTANT: The config files will be automatically created if you reload the Configs
# Set the Default Tablist in /plugins/MyTabList2/worlds/default.yml

#
# Define Header & Footer Text for Minecraft 1.8 Users
#
tabheader: ''
tabfooter: ''
